### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by osmoc** [guyzmo/event-source-library#12]
There are few things which seem dated in the existing documentation:
* it refers to eventsource_listener which it's actually located in ./eventsource/listener.py
* KEEPALIVE setting does not mention unit (seconds? minutes?)
* incompatible examples: server uses -P 8888 setting while client doesn't so trying to follow it will lead to cryptic error:

Traceback (most recent call last):
  File "client.py", line 139, in handle_stream
    (field, value) = line.split(":", 1)
ValueError: need more than 1 value to unpack
ERROR:eventsource.client:HTTP 599: Failed writing body (0 != 877)

The right entry would be "python client.py 42:42:42:42:42:42 -r 5000 -P 8888"
* both client and requestor use 'token' but it's not clear why it is mandatory
* the r"/(.*)/(.*)" argument to tornado.web.Application looks mysterious - some reference to what it is would be helpful
* likely a typo: class OneLineIdEvent(OneLineEvent,IdEvent) -> class OneLineIdEvent(OneLineEvent,EventId)

**Comment by guyzmo** [comment]
Hello, as you might have noticed, this piece of code is about 3 years old… So I'm sorry if I don't remember well the specifics, and even more sorry if at the time I did not update the documentation properly! ☹

Don't hesitate to make a PR to update the doc, or fix the code where it matters.!

That being said:

> [the doc] refers to eventsource_listener which it's actually located in ./eventsource/listener.py

you're right this is wrong: it's actually `eventsource_server`, which gets installed by `setup.py`. You can install it by using `python setup.py install`.

> `KEEPALIVE` setting does not mention unit (seconds? minutes?)

I did not check the code, but knowing myself, it's very likely to be in seconds.

> incompatible examples: server uses `-P 8888` setting while client doesn't so trying to follow it will lead to cryptic error: …

ah, at first I did not understand. There's actually two issues here:

* the documentation should be consistent and have the matching `-P 8888` for the client (good catch) ;
* the code should throw a human understandable error when it cannot reach a server (instead of a cryptic `ValueError`.

> both client and requestor use 'token' but it's not clear why it is mandatory

Well, that's what the example shows off: the default implementation of the code (client/listener/request) is that you start sessions between *listener* and *clients*, and you send data to the clients by using *request*. When you send a *request* the token is used to identify which client to send a message to.

Of course, you can use this code as a library from your own code, so you can implement your own actions instead of the default behavior. *And I actually encourage to do that!*

> the `r"/(.)/(.)"` argument to tornado.web.Application looks mysterious - some reference to what it is would be helpful

There I do not agree, it's well explained in tornado's documentation:

* http://www.tornadoweb.org/en/stable/web.html#application-configuration

> *The constructor for this class takes in a list of URLSpec objects or (regexp, request_class) tuples.*
> *When we receive requests, we iterate over the list in order and instantiate an instance of the first request class whose regexp matches the request path.*

so it's basically the URLSpec that matches on what API the library is listening on. Per default, it's any path that has two parts.

> likely a typo: `class OneLineIdEvent(OneLineEvent,IdEvent)` -> `class OneLineIdEvent(OneLineEvent,EventId)`

good catch.

**Comment by guyzmo** [comment]
About:

>    incompatible examples: server uses -P 8888 setting while client doesn't so trying to follow it will lead to cryptic error:
>
> ```
Traceback (most recent call last):
File "client.py", line 139, in handle_stream
(field, value) = line.split(":", 1)
ValueError: need more than 1 value to unpack
ERROR:eventsource.client:HTTP 599: Failed writing body (0 != 877)
```
>
> The right entry would be "python client.py 42:42:42:42:42:42 -r 5000 -P 8888"

I couldn't reproduce. Could you show me how you ended up having that exact traceback?

Actually, could you open a new issue regarding only this?

**Comment by osmoc** [comment]
Thanks for quick response!

I've noticed that the code is rather dated but it's still the best I could find and the license is perfect. :)

Thanks for fixes and link to tornado docs. I'll try to follow-up with PR shortly.

**Comment by osmoc** [comment]
> I did not check the code, but knowing myself, it's very likely to be in seconds.

Seems like it's milliseconds: see http://www.tornadoweb.org/en/stable/ioloop.html for tornado.ioloop.PeriodicCallback() which is called with int(keepalive) in listener.py

**Comment by guyzmo** [comment]
ok, good spot, I agree it's worth documenting there:

* https://github.com/guyzmo/event-source-library/blob/master/eventsource/listener.py#L161

if you could make it a PR I'd appreciate it ☺

also make a PR to add you to the README for crediting you on the doc patches! :-)

* https://github.com/guyzmo/event-source-library/blob/master/README.rst#licensing

**Comment by osmoc** [comment]
PR created, please have a look.
